library(dplyr)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",
	      temp)
data <- read.table(unz(temp, "household_power_consumption.txt"),
		   sep=";", header = TRUE)
unlink(temp)
data <- subset(data,data$Date=="1/2/2007" | data$Date =="2/2/2007")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
data$Time <- strptime(data$Time, format="%H:%M:%S")
data[1:1440,"Time"] <- format(data[1:1440,"Time"],"2007-02-01 %H:%M:%S")
data[1441:2880,"Time"] <- format(data[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(data$Time,as.numeric(as.character(data$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)") 
dev.copy(png, filename="plot2.png",width=480,height=480)
dev.off()
